Repository tesseract-ocr/tesseract, pull requests merged in 2019-05, with the labels that each got.

#2419 Fix some typos (most found and fixed by codespell)
  src/api/pdfrenderer.cpp
  src/ccmain/equationdetect.cpp
  src/ccmain/equationdetect.h
  src/textord/cjkpitch.cpp
  src/textord/colpartitionset.cpp
  src/textord/colpartitionset.h
  src/textord/tordmain.cpp
  unittest/intfeaturemap_test.cc
  unittest/paragraphs_test.cc
Labels: review

#2420 Fix more locale dependencies
  src/ccmain/paramsd.cpp
  src/classify/clusttool.cpp
  src/classify/clusttool.h
  src/training/commandlineflags.cpp
Labels: review

#2421 universalambigs: Add missing include file
  src/ccutil/universalambigs.cpp
Labels: review

#2422 tesscallback: Remove unused code
  src/ccutil/tesscallback.h
Labels: review

#2430 Fix reading of parameter from traineddata normproto component and make function independent of locale
  src/classify/clusttool.cpp
Labels: bug, review

#2434 configure: Fix for latest developer tools on macOS
  configure.ac
Labels: review

#2437 Fix some unittests with locale de_DE.UTF-8
  src/api/baseapi.cpp
  src/ccutil/unicharset.cpp
  src/classify/normmatch.cpp
Labels: review

#2432 Add different classes to hocr output depending on BlockType
  src/api/hocrrenderer.cpp
Labels: output

#2440 Fix linker error for baseapi_test when building without legacy engine
  unittest/baseapi_test.cc
Labels: review

#2441 Fix unittest build without legacy code and use locale for most unittests
  unittest/Makefile.am
  unittest/baseapi_test.cc
  unittest/bitvector_test.cc
  unittest/colpartition_test.cc
  unittest/commandlineflags_test.cc
  unittest/dawg_test.cc
  unittest/denorm_test.cc
  unittest/equationdetect_test.cc
  unittest/heap_test.cc
  unittest/imagedata_test.cc
  unittest/indexmapbidi_test.cc
  unittest/intfeaturemap_test.cc
  unittest/intsimdmatrix_test.cc
  unittest/ligature_table_test.cc
  unittest/linlsq_test.cc
  unittest/lstm_test.h
  unittest/mastertrainer_test.cc
  unittest/matrix_test.cc
  unittest/networkio_test.cc
  unittest/nthitem_test.cc
  unittest/osd_test.cc
  unittest/pango_font_info_test.cc
  unittest/params_model_test.cc
  unittest/qrsequence_test.cc
  unittest/recodebeam_test.cc
  unittest/rect_test.cc
  unittest/scanutils_test.cc
  unittest/shapetable_test.cc
  unittest/stats_test.cc
  unittest/stridemap_test.cc
  unittest/stringrenderer_test.cc
  unittest/tablefind_test.cc
  unittest/tablerecog_test.cc
  unittest/tabvector_test.cc
  unittest/tatweel_test.cc
  unittest/tfile_test.cc
  unittest/unicharcompress_test.cc
  unittest/unicharset_test.cc
Labels: review

#2444 fix typo
  CMakeLists.txt
Labels: review

#2461 Support build with Tensorflow
  configure.ac
  src/api/Makefile.am
  src/ccutil/unicharset.h
  src/lstm/Makefile.am
  src/lstm/tfnetwork.cpp
  src/lstm/tfnetwork.h
  src/lstm/tfnetwork.pb.cc
  src/lstm/tfnetwork.pb.h
  src/lstm/tfnetwork.proto
  src/training/Makefile.am
  src/training/tesstrain_utils.py
  src/training/tesstrain_utils.sh
  unittest/Makefile.am
Labels: feature request
